const aliasesInitialObject = {
    "Augustus Gloop": "available",
    "Baby Yoda": "available",
    "BeachBabe181": "available",
    "Ben Derhover": "available",
    "Ben Geller": "available",
    "Buddy the Elf": "available",
    "Butler Albert": "available",
    "Carl Wheezer": "available",
    "DONKEY": "available",
    "Daddy Napolean": "available",
    "Darth Evader": "available",
    "Dixie Normous": "available",
    "Doug Judy": "available",
    "Dwight Shrute": "available",
    "Elliot Moose": "available",
    "Fawn Dilenmibals": "available",
    "Fedora Explora": "available",
    "Ford Tough": "available",
    "GarBear007": "available",
    "George Shrinks": "available",
    "Gordon Ramsay": "available",
    "Hagrid's Owl": "available",
    "Hakuna Matata": "available",
    "Hey It's Franklin": "available",
    "Hugh Neutron": "available",
    "Iron Fist": "available",
    "Jack B Nimble": "available",
    "Janice Hosenstein": "available",
    "Lord Farquad": "available",
    "Miya Butreaks": "available",
    "Moist Thunder": "available",
    "Mom's Spaghetti": "available",
    "Mr Paninos": "available",
    "Mucho Grande": "available",
    "Nestea Cool": "available",
    "Old Greg": "available",
    "Papa John": "available",
    "Regina George": "available",
    "Rolie Polie Olie": "available",
    "Ron Swanson": "available",
    "Ron Weasely": "available",
    "Squidward": "available",
    "ThisIsAPingo": "available",
    "Tutin Putin": "available",
    "Waluigi Wah!": "available",
    "Willy Wonka": "available"
}

export default aliasesInitialObject;